version: "3.7"

services:
  db:
    image: postgres
    env_file:
      - .env
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    env_file:
      - .env
    volumes:
      - ./:/usr/src/app/
  redis:
    image: redis:alpine
  celery:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A TradingPlatform worker -B -E -l INFO
    env_file:
       - .env
    depends_on:
      - redis
      - web
    volumes:
      - ./:/usr/src/app/
